{{- if not .Values.existingSecret }}
{{- $config := deepCopy .Values.ingress }}
{{- $_ := unset $config "secrets" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ingress.fullname" . }}
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml $config | indent 4 }}
{{- end }}
