{{- if and .Values.storeSecretsInSecret.enabled (not .Values.storeSecretsInSecret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingress.fullname" . }}
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.ingress | b64enc }}
{{- end }}
