{{- if not .Values.existingSecret }}
{{- $config := deepCopy .Values.ingress }}
{{- $secrets := $config.secrets | default dict }}
{{- $_ := unset $config "secrets" }}
{{- $merged := mustMergeOverwrite $config $secrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ingress.fullname" . }}
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml $merged | b64enc }}
{{- end }}
