{{- if and .Values.serviceMonitor.create .Values.ingress.prometheus_port -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "ingress.serviceMonitorName" . }}
  labels:
    {{- include "ingress.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: metrics
      path: /
      interval: {{ .Values.serviceMonitor.interval }}
  selector:
    matchLabels:
      {{- include "ingress.selectorLabels" . | nindent 6 }}
{{- end }}
