apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress.fullname" . }}
  labels: {{- include "ingress.labels" . | nindent 4 }}
spec:
  type: {{ default "LoadBalancer" .Values.ingress.serviceType }}
  ports:
    {{- if .Values.loadBalancer.servicePort }}
    - port: {{ .Values.loadBalancer.servicePort }}
      protocol: TCP
      name: ws
    {{- end }}
    - port: {{ .Values.ingress.rtmp_port }}
      protocol: TCP
      name: rtmp
    - port: {{ .Values.ingress.whip_port }}
      protocol: TCP
      name: whip

  selector:
    {{- include "ingress.selectorLabels" . | nindent 4 }}
