apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress.fullname" . }}
  labels: {{- include "ingress.labels" . | nindent 4 }}
spec:
  type: {{ default "LoadBalancer" .Values.ingress.serviceType }}
  ports:
    - port: {{ .Values.loadBalancer.servicePort }}
      protocol: TCP
      name: ws
    - port: {{ .Values.ingress.rtmp_port }}
      protocol: TCP
      name: rtmp
  selector:
    {{- include "ingress.selectorLabels" . | nindent 4 }}