apiVersion: v1
kind: Service
metadata:
  name: {{ include "ingress.fullname" . }}
  labels: {{- include "ingress.labels" . | nindent 4 }}
  {{- if eq .Values.loadBalancer.type "aws" }}
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-backend-protocol: http
    service.beta.kubernetes.io/aws-load-balancer-type: nlb
  {{- else if or (eq .Values.loadBalancer.type "gke") (eq .Values.loadBalancer.type "gke-managed-cert") }}
  annotations:
    cloud.google.com/backend-config: '{"ports": {"{{ .Values.loadBalancer.servicePort }}":"{{ include "ingress.fullname" . }}"}}'
  {{- end }}
spec:
  {{- if or (eq .Values.loadBalancer.type "alb") (eq .Values.loadBalancer.type "gke") (eq .Values.loadBalancer.type "gke-managed-cert") (eq .Values.loadBalancer.type "do") }}
  type: NodePort
  {{- else }}
  type: LoadBalancer
  {{- end }}
  ports:
    - port: {{ .Values.loadBalancer.servicePort }}
      protocol: TCP
      name: ws
    - port: {{ .Values.ingress.rtmp_port }}
      protocol: TCP
      name: rtmp
  selector:
    {{- include "ingress.selectorLabels" . | nindent 4 }}