{{- if and .Values.storeSecretsInSecret.enabled (not .Values.storeSecretsInSecret.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "egress.fullname" . }}
  labels:
    {{- include "egress.labels" . | nindent 4 }}
type: Opaque
data:
  config.yaml: {{ toYaml .Values.egress | b64enc }}
{{- end }}
