apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "livekit-server.fullname" . }}
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
data:
  config.yaml: |
{{ toYaml .Values.livekit | indent 4 }}
