{{- if .Values.optimizeNetwork -}}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "livekit-server.fullname" . }}-sysctl
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "livekit-server.name" . }}-sysctl
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "livekit-server.name" . }}-sysctl
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      hostPID: true
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - name: daemonset
        image: cilium/startup-script:2de58e53a7060593c91d0655b337a57f06bf5d66-dev        
        imagePullPolicy: Always
        securityContext:
          privileged: true
        env:
        - name: STARTUP_SCRIPT
          value: |
            #! /bin/bash
            set -x
            sysctl -w vm.max_map_count=262144
            sysctl -w fs.file-max=2097152
            sysctl -w net.core.somaxconn=65535
            sysctl -w net.core.netdev_max_backlog=65536
            sysctl -w net.core.optmem_max=25165824
            sysctl -w net.core.rmem_max=25165824
            sysctl -w net.core.wmem_max=25165824
            sysctl -w net.core.rmem_default=1048576
            sysctl -w net.core.wmem_default=1048576
            sysctl -w net.ipv4.udp_mem="65536 131072 262144"
            sysctl -w net.ipv4.udp_rmem_min=16384
            sysctl -w net.ipv4.udp_wmem_min=16384
            sysctl -w net.ipv4.tcp_tw_reuse=1
            sysctl -w fs.inotify.max_user_instances=524288
            echo "done"
{{- end }}
