{{- if and (not .Values.keyFile.existingSecret) .Values.keyFile.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "livekit-server.fullname" . }}-keys
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
data:
  {{  .Values.livekit.key_file }}: {{ toYaml .Values.keyFile.keys | b64enc }}
{{- end }}
