{{- if and (not .Values.storeKeysInSecret.existingSecret) .Values.storeKeysInSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "livekit-server.fullname" . }}
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
data:
  {{  .Values.livekit.key_file }}: {{ toYaml .Values.storeKeysInSecret.keys | b64enc }}
{{- end }}
