{{- if .Values.keyFile.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "livekit-server.fullname" . }}-keys
data:
  keys.yaml: {{ toYaml .Values.keyFile.keys | b64enc }}
{{- end }}
