{{- if .Values.keyFile.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "livekit-server.fullname" . }}-keys
data:
  {{  .Values.keyFile.fileName }}: {{ toYaml .Values.keyFile.keys | b64enc }}
{{- end }}
