{{- if and .Values.serviceMonitor.create (include "livekit-server.prometheus_port" .) -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "livekit-server.serviceMonitorName" . }}
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
  {{- with .Values.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  endpoints:
    - port: metrics
      path: /
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if and .Values.livekit.prometheus.username .Values.livekit.prometheus.password }}
      basicAuth:
        password:
          name: {{ include "livekit-server.serviceMonitorSecretName" . }}
          key: password
        username:
          name: {{ include "livekit-server.serviceMonitorSecretName" . }}
          key: username
      {{- end }}
  selector:
    matchLabels:
      {{- include "livekit-server.selectorLabels" . | nindent 6 }}
{{- end }}
