{{- if and .Values.serviceMonitor.create .Values.livekit.prometheus .Values.livekit.prometheus.username .Values.livekit.prometheus.password }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "livekit-server.serviceMonitorSecretName" . }}
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
data:
    username: {{ .Values.livekit.prometheus.username | b64enc }}
    password: {{ .Values.livekit.prometheus.password | b64enc }}
{{- end }}
