{{- if and .Values.livekit.turn.enabled .Values.livekit.turn.tls_port }}
apiVersion: v1
kind: Service
metadata:
  name: '{{ include "livekit-server.fullname" . }}-turn'
  labels:
    {{- include "livekit-server.labels" . | nindent 4 }}
  {{- with .Values.livekit.turn.loadBalancerAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if not .Values.livekit.turn.external_tls }}
  type: LoadBalancer
  {{- end }}
  ports:
    - port: 443
      targetPort: {{ .Values.livekit.turn.tls_port }}
      protocol: TCP
  selector:
    {{- include "livekit-server.selectorLabels" . | nindent 4 }}
{{- end }}
