apiVersion: v2
name: livekit-server
description: Open source WebRTC infrastructure. Host your own real-time video/audio experiences.
type: application
version: 1.3.5
appVersion: "v1.3.5"

sources:
  - https://github.com/livekit/livekit
