apiVersion: v2
name: livekit-server
description: Open source WebRTC infrastructure. Host your own real-time video/audio experiences.
type: application
version: 1.4.3
appVersion: "v1.4.3"

sources:
  - https://github.com/livekit/livekit
