# based on: https://github.com/nats-io/k8s/blob/main/.github/workflows/test.yaml and https://github.com/helm/charts-repo-actions-demo/blob/main/.github/workflows/lint-test.yaml
name: Lint, Install, and Test Charts

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'ingress/**'
      - 'egress/**'
      - 'livekit-server/**'
      - '.github/workflows/test.yaml'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        k8s:
          - "1.26"
          - "1.25"
          - "1.24"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.11.2

      # Python is required because `ct lint` runs Yamale (https://github.com/23andMe/Yamale) and
      # yamllint (https://github.com/adrienverge/yamllint) which require Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.6.1

      - name: Run chart-testing (lint)
        run: |-
          ct lint \
            --all \
            --chart-dirs egress ingress livekit-server \
            --validate-maintainers=false

      - name: Create k8s cluster
        run: |-
          sudo snap install microk8s --channel="${{ matrix.k8s }}/stable" --classic
          sudo microk8s.enable dns hostpath-storage
          sudo microk8s.kubectl wait --for=condition=ready --timeout=60s node --all
          sudo microk8s.kubectl wait --for=condition=ready --timeout=120s --namespace=kube-system pod --all
          mkdir -p ~/.kube
          sudo microk8s.config > ~/.kube/config
          chmod 600 ~/.kube/config

      - name: Run chart-testing (install)
        run: |-
          ct install \
            --all \
            --chart-dirs egress ingress livekit-server
